### ISSUE TITLE
Save operation failed on AWS

### ISSUE THREAD

**Issue by martinspain** [aelvan/Imager-Craft#147]
I've recently added WebP support to my project and it works in my OS X local dev environment perfectly. However, I get the following error on our AWS staging server:

`
2017/12/22 10:35:44 [error] [exception.Twig_Error_Runtime] Craft\Exception: Save operation failed in /var/app/current/craft/plugins/imager/services/ImagerService.php:1213
Stack trace:
#0 /var/app/current/craft/plugins/imager/services/ImagerService.php(539): Craft\ImagerService->_saveAsWebp(Object(Imagine\Imagick\Image), '/var/www/html/p...', 'png', Array)
#1 /var/app/current/craft/plugins/imager/services/ImagerService.php(341): Craft\ImagerService->_getTransformedImage(Object(Craft\Imager_ImagePathsModel), Array)
`

Is there any way to get more detailed information on _why_ the save operation failed? There's plenty of disk space available and I've set PHP's memory limit to 512M - does Imager need more memory than this for these sorts of transforms?

**Comment by martinspain** [comment]
Doubled the memory allocation to 1GB and that seems to have resolved it!
