### ISSUE TITLE
500 error thrown when Imager fed a PSD renamed as JPG

### ISSUE THREAD

**Issue by natebeaty** [aelvan/Imager-Craft#185]
A client managed to crash the site by uploading an 8.9mb PSD renamed as a JPG, which obviously shouldn't happen, but I would hope such an error wouldn't crash the entire site.

Thought I'd pass this along, and also ask if there's a way to avoid this causing a 500 error, and possibly just getting a null return on `treatedImage` instead.

This is the template code:

```
{% if pageHeader.image|length %}
  {% set headerImage = pageHeader.image.one() %}
  {% set treatedImage = craft.imager.transformImage(headerImage, {
    width: 1000,
    height: 1000,
    mode: 'crop',
    position: '20% 65%',
    effects: { modulate: [100, 0, 100], clut: 'gradient:#222222-#ffffff' }
  }) %}
{% endif %}
...
{% if pageHeader.image|length %}
  <div class="image" style="background-image: url({{ treatedImage ? treatedImage.getUrl() : '' }});"></div>
{% endif %}

```

...and error log below:

```
2018-08-08 10:33:28 [2603:300a:5a3:1000:bd92:abcf:5364:9ef4][-][cc6f4c8b2708ca277bcc6a0d0ae37f35][error][TypeError] TypeError: Argument 1 passed to Imagine\Imagick\Image::applyImageOptions() must be an instance of Imagine\Imagick\Imagick, instance of Imagick given, called in /home/username/webapps/appname/vendor/pixelandtonic/imagine/lib/Imagine/Imagick/Image.php on line 433 and defined in /home/username/webapps/appname/vendor/pixelandtonic/imagine/lib/Imagine/Imagick/Image.php:743
Stack trace:
#0 /home/username/webapps/appname/vendor/pixelandtonic/imagine/lib/Imagine/Imagick/Image.php(433): Imagine\Imagick\Image->applyImageOptions(Object(Imagick), Array, '/home/username...')
#1 /home/username/webapps/appname/vendor/pixelandtonic/imagine/lib/Imagine/Imagick/Image.php(317): Imagine\Imagick\Image->prepareOutput(Array, '/home/username...')
#2 /home/username/webapps/appname/vendor/aelvan/imager/src/transformers/CraftTransformer.php(313): Imagine\Imagick\Image->save('/home/username...', Array)
#3 /home/username/webapps/appname/vendor/aelvan/imager/src/transformers/CraftTransformer.php(90): aelvan\imager\transformers\CraftTransformer->getTransformedImage(Object(aelvan\imager\models\LocalSourceImageModel), Array)
#4 /home/username/webapps/appname/vendor/aelvan/imager/src/services/ImagerService.php(329): aelvan\imager\transformers\CraftTransformer->transform(Object(craft\elements\Asset), Array)
#5 /home/username/webapps/appname/vendor/aelvan/imager/src/variables/ImagerVariable.php(37): aelvan\imager\services\ImagerService->transformImage(Object(craft\elements\Asset), Array, NULL, NULL)
#6 /home/username/webapps/appname/vendor/twig/twig/lib/Twig/Extension/Core.php(1619): aelvan\imager\variables\ImagerVariable->transformImage(Object(craft\elements\Asset), Array)
#7 /home/username/webapps/appname/vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(aelvan\imager\variables\ImagerVariable), 'transformImage', Array, 'method', false, false)
#8 /home/username/webapps/appname/storage/runtime/compiled_templates/ee/ee99159ae925c197823d7ec1b3ab4fd76fb5a3ded05f49c2cb989029ee512666.php(36): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(aelvan\imager\variables\ImagerVariable), 'transformImage', Array, 'method')
#9 /home/username/webapps/appname/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_3c98d579e92e93ccab9f833fa6368fa571b63938f14e7aff23376e80d2ac32d5->doDisplay(Array, Array)
#10 /home/username/webapps/appname/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#11 /home/username/webapps/appname/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#12 /home/username/webapps/appname/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#13 /home/username/webapps/appname/storage/runtime/compiled_templates/43/43322409215c4afc82beef933246c10be040d894125cd475977ffaaef27a5857.php(64): craft\web\twig\Template->display(Array)
#14 /home/username/webapps/appname/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_b0f9a9cc7f03a2234afa5d2eb52e80e34b54d3d1628494f0ae95c8854fc2cf57->block_content(Array, Array)
#15 /home/username/webapps/appname/storage/runtime/compiled_templates/62/620eb1861057df33fe28eed4b815a8af207def187ec70da37a182da2f6b3c7d5.php(91): Twig_Template->displayBlock('content', Array, Array)
#16 /home/username/webapps/appname/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_305fb7ebcfb39f133203b1fbe503644146fb06137afe2fd4c13e5d07762d0cf7->doDisplay(Array, Array)
#17 /home/username/webapps/appname/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#18 /home/username/webapps/appname/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#19 /home/username/webapps/appname/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#20 /home/username/webapps/appname/storage/runtime/compiled_templates/43/43322409215c4afc82beef933246c10be040d894125cd475977ffaaef27a5857.php(54): craft\web\twig\Template->display(Array, Array)
#21 /home/username/webapps/appname/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_b0f9a9cc7f03a2234afa5d2eb52e80e34b54d3d1628494f0ae95c8854fc2cf57->doDisplay(Array, Array)
#22 /home/username/webapps/appname/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#23 /home/username/webapps/appname/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#24 /home/username/webapps/appname/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#25 /home/username/webapps/appname/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#26 /home/username/webapps/appname/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#27 /home/username/webapps/appname/vendor/craftcms/cms/src/web/View.php(330): Twig_Environment->render('about/index', Array)
#28 /home/username/webapps/appname/vendor/craftcms/cms/src/web/View.php(377): craft\web\View->renderTemplate('about/index', Array)
#29 /home/username/webapps/appname/vendor/craftcms/cms/src/web/Controller.php(155): craft\web\View->renderPageTemplate('about/index', Array)
#30 /home/username/webapps/appname/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('about/index', Array)
#31 [internal function]: craft\controllers\TemplatesController->actionRender('about/index', Array)
#32 /home/username/webapps/appname/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#33 /home/username/webapps/appname/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#34 /home/username/webapps/appname/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('render', Array)
#35 /home/username/webapps/appname/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#36 /home/username/webapps/appname/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('templates/rende...', Array)
#37 /home/username/webapps/appname/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#38 /home/username/webapps/appname/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#39 /home/username/webapps/appname/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#40 /home/username/webapps/appname/web/index.php(21): yii\base\Application->run()
#41 {main}
2018-08-08 10:33:24 [2603:300a:5a3:1000:bd92:abcf:5364:9ef4][-][cc6f4c8b2708ca277bcc6a0d0ae37f35][info][application] $_GET = [
    'p' => 'about/'
]
```

**Comment by aelvan** [comment]
If you don't have it enabled, you could try setting [`suppressExceptions`](https://github.com/aelvan/Imager-Craft#suppressexceptions-bool) to true. That should result in Imager returning null instead of an exception if something goes wrong, _most of the time_. Some types of errors are not easily catched, and this may be one of them. But try it, and let me know if it doesn't work, and I'll have a look.

**Comment by natebeaty** [comment]
I tried it both in `config/imager.php` and directly in the template on the `transformImage()` call and still got the same error.

Just curious, won't this line https://github.com/aelvan/Imager-Craft/blob/craft3/src/models/Settings.php#L162 override whatever you put in `config/imager.php` and just set it to `!devMode`?

Not a huge deal, as hopefully people renaming PSDs with a JPG extension and uploading to Craft is an uncommon issue.

**Comment by aelvan** [comment]
I dug into this, and turns out that this would actually have worked, but there's a small bug, either in P&T's fork of the Imagine, or in the base library, that makes the error. For some reason, when opening a PSD with a jpg extension, the resulting imagick instance inside Imagick is of type `\Imagick`, whereas it usually is `Imagine\Imagick\Imagick`. In P&T's fork of Imagine, the type hinting in the method signature requires `Imagine\Imagick\Imagick` so it balks with the error above when `\Imagick` is passed in.

I'll make P&T aware, but not sure if it's something they can fix.

**Comment by fleaz** [comment]
Hi,
sorry, for commenting on such an old issue.
We also ran into this "uncommon issue"  yesterday because on of our customers did exactly the same (uploading a psd with '.jpg' filename extension) and killed it's whole site due to this issue :D

@aelvan  Did you got a response from P&T regarding this?

**Comment by natebeaty** [comment]
Fwiw the same client did this again months after site launch, which still bombs the request with a 500 error. I had to manually dig through all the images on the page and find one that was a renamed psd to fix it.

**Comment by sjcallender** [comment]
Just had this issue happen to us too on a Craft 3.2.5.1 site with Imager 2.1.10.
